name: Hugo Build and Deploy

on:
  push:
    branches: [ "main", "actions_dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hugo-build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      - name: Install Hugo
        run: sudo apt install -y hugo
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          service_account: 'github-actions@github-exploration-442503.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/641246862184/locations/global/workloadIdentityPools/github/providers/nmcguirt-github'
      - name: Hugo build
        run: hugo --minify
      - name: Deploy to GCS
        run: gcloud storage rsync --recursive $GITHUB_WORKSPACE/public/ ${{vars.prod_bucket}} --dryrun


      




