name: Hugo Build and Deploy

on:
  push:
    branches: [ "main", "actions_dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hugo-build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          service_account: 'github-actions@github-exploration-442503.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/641246862184/locations/global/workloadIdentityPools/github/providers/nmcguirt-github'
      # - uses: docker://ghcr.io/gohugoio/hugo:v0.139.3
      #   name: Hugo Build
      #   with:
      #     args: "--minify"
      - name: Hugo Container Run
        run: |
          /usr/bin/docker run \
          -v "$(pwd):/project" \
          docker://ghcr.io/gohugoio/hugo:v0.139.3 \
          "--minify"





