name: Hugo Build and Deploy

on:
  push:
    branches: [ "main", "actions_dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hugo-build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    environment:
      name: production
      
    steps:
      - name: Install Hugo
        run: sudo apt install -y hugo
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          service_account: 'github-actions@github-exploration-442503.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/641246862184/locations/global/workloadIdentityPools/github/providers/nmcguirt-github'
      - name: Debug - Hugo Help
        run: hugo --help
      - name: Debug - Show files
        run: find $GITHUB_WORKSPACE
      - name: Debug - Hugo config
        run: hugo -s $GITHUB_WORKSPACE --config hugo.yaml config
      - name: Hugo build
        run: |
          hugo -s $GITHUB_WORKSPACE \
          --config hugo.yaml \
          --contentDir $GITHUB_WORKSPACE/content
          --themesDir $GITHUB_WORKSPACE/themes
      - name: Debug - Show files
        run: find $GITHUB_WORKSPACE
      - name: Deploy to GCS
        run: gcloud storage rsync --recursive $GITHUB_WORKSPACE/public/ ${{ vars.BUCKET }} --dryrun
